services:
  - type: worker
    name: kinobot-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SUPER_ADMIN_ID
        sync: false
